### ISSUE TITLE
Status of searching for a maintainer

### ISSUE THREAD

**Issue by viktorbenei** [vongrippen/bitbucket#43]
Hi,

Can you share with us what's the status? Are you still searching for a new maintainer?

This is quite an urgent issue as Bitbucket started to migrate to it's new V2 API - for example you can't register a V1 webhook from the Bitbucket web UI anymore - and your GEM is still by far the most popular one.

**Comment by vongrippen** [comment]
I have not found a new maintainer yet, but would definitely like to find one for the project since I know so many people use the gem. If all else fails, I might find the time to quickly try to update the main parts to the V2 API since V1 is starting to see some deprecation.

**Comment by viktorbenei** [comment]
Thanks for the quick reply @vongrippen !
If you don't mind, do you still use this gem for your projects?

We would be interested in the maintenance of this gem but unfortunately right now we don't have the required resources to fully commit.

One quick requires if you have the time, could you please update the gem's dependencies? We're stuck with an older version of our github gem (https://github.com/peter-murach/github) because of older dependencies locked in your Bitbucket API gem.

**Comment by vongrippen** [comment]
I'm not using it in any of my projects anymore. Well, not directly at least. I am using errbit and a bitbucket plugin now that apparently uses my gem.

Let me know what dependencies are a problem and I can take a look at it. Depending on what it is, I might just need to loosen the constraints a little bit without much further change. I'd also be happy to merge pull requests if you have a little time to work on things, but not enough for full on maintenance.

**Comment by viktorbenei** [comment]
I'll check the exact dependency versions tomorrow, thank you!

**Comment by viktorbenei** [comment]
Pull Requests: we actually don't have an issue with this current version, it worked perfectly so far. If we find anything we could fix/improve we'll definitely open a PR for it, but we don't have the time to do a full V2 API support unfortunately. At least not right now :/

**Comment by viktorbenei** [comment]
So this is what I get if I try to upgrade to the latest `github_api` gem (v0.12.3):

```
Bundler could not find compatible versions for gem "hashie":
  In Gemfile:
    hashie (< 4, >= 1.2) ruby

    bitbucket_rest_api (>= 0) ruby depends on
      hashie (~> 2.0.5) ruby

    github_api (= 0.12.3) ruby depends on
      hashie (>= 3.3) ruby
```

I saw you already updated this dependency but it's not in the current release, I think this is the only dependency which prevents the upgrade of the `github_api` gem.

**Comment by vongrippen** [comment]
I'll try to push a new release to rubygems today. I've needed to for a long time, there's several things that aren't released yet that have been merged

**Comment by viktorbenei** [comment]
Thank you @vongrippen , we really appreciate your energy put into creating this awesome gem! We never had any issue using it, that's why we hoped that you or someone who's experienced with the code might be able to keep maintaining it :)

Once again, thank you for your time and for your quick response!

**Comment by vongrippen** [comment]
I just pushed 0.1.7 up to rubygems. That should let yet use the latest github_api gem with it.

**Comment by viktorbenei** [comment]
Thanks @vongrippen , just upgraded it (and the `github_api` gem as well)!
