### ISSUE TITLE
Question - How I can each all pages of result?

### ISSUE THREAD

**Issue by rgarbin** [vongrippen/bitbucket#45]
prs = bitbucket.repos.pull_request.list('zenvia-sms', application, { "state" => "MERGED, OPEN,  DECLINED" })

prs['values'].each do |pr|
   //only first page
end

**Comment by vongrippen** [comment]
In the params, you can specify the page to return and the response will
have a "page" key.

prs = bitbucket.repos.pull_request.list('zenvia-sms', application, {
"state" => "MERGED, OPEN, DECLINED", "page" => 2 })

I believe you can also specify the response size with the "size" parameter.

------------------------------------------------------
Mike Cochran
mcochran@linux.com

**Comment by rgarbin** [comment]
Thanks a lot @vongrippen
